In [88]:
import pandas as pd

df = pd.read_csv("data/cleaned/04_shared/master_cleaned.csv")

In [89]:
print(df.columns)

Index(['city', 'state', 'latitude', 'longitude', 'datetime', 'month',
       'day_name', 'is_weekend', 'season', 'time_of_day', 'humidity_percent',
       'dew_point_c', 'wind_gusts_kmh', 'precipitation_mm', 'is_raining',
       'heavy_rain', 'pressure_msl_hpa', 'cloud_cover_percent', 'pm2_5_ugm3',
       'pm10_ugm3', 'co_ugm3', 'no2_ugm3', 'so2_ugm3', 'o3_ugm3', 'dust_ugm3',
       'aod', 'us_aqi', 'aqi_category', 'pm25_category_india',
       'festival_period', 'crop_burning_season', 'hour', 'day_of_week'],
      dtype='str')

In [90]:
df['AQI'] = df['us_aqi']

In [91]:
df = df.sort_values(['city', 'datetime'])

In [92]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['city_enc'] = le.fit_transform(df['city'])

In [93]:
import joblib
joblib.dump(le, "models/city_encoder.pkl")

['models/city_encoder.pkl']

### STEP 4 — Create lag features

In [94]:
for lag in [1, 6, 24]:
    df[f'AQI_lag_{lag}'] = df.groupby('city')['AQI'].shift(lag)

### STEP 5 — Create future targets

In [95]:
df['AQI_next_6']  = df.groupby('city')['AQI'].shift(-6)
df['AQI_next_12'] = df.groupby('city')['AQI'].shift(-12)
df['AQI_next_24'] = df.groupby('city')['AQI'].shift(-24)

In [96]:
df[['city','datetime','AQI','AQI_lag_1','AQI_lag_6','AQI_lag_24']].head(40)

        city             datetime    AQI  AQI_lag_1  AQI_lag_6  AQI_lag_24
0   agartala  2022-08-05 00:00:00  289.0        NaN        NaN         NaN
1   agartala  2022-08-05 01:00:00  289.0      289.0        NaN         NaN
2   agartala  2022-08-05 02:00:00   54.0      289.0        NaN         NaN
3   agartala  2022-08-05 03:00:00   54.0       54.0        NaN         NaN
4   agartala  2022-08-05 04:00:00   54.0       54.0        NaN         NaN
5   agartala  2022-08-05 05:00:00   54.0       54.0        NaN         NaN
6   agartala  2022-08-05 06:00:00   55.0       54.0      289.0         NaN
7   agartala  2022-08-05 07:00:00   55.0       55.0      289.0         NaN
8   agartala  2022-08-05 08:00:00   55.0       55.0       54.0         NaN
9   agartala  2022-08-05 09:00:00   54.0       55.0       54.0         NaN
10  agartala  2022-08-05 10:00:00   55.0       54.0       54.0         NaN
11  agartala  2022-08-05 11:00:00   55.0       55.0       54.0         NaN
12  agartala  2022-08-05 12:00:00   55.0       55.0       55.0         NaN
13  agartala  2022-08-05 13:00:00   56.0       55.0       55.0         NaN
14  agartala  2022-08-05 14:00:00   56.0       56.0       55.0         NaN
15  agartala  2022-08-05 15:00:00   56.0       56.0       54.0         NaN
16  agartala  2022-08-05 16:00:00   56.0       56.0       55.0         NaN
17  agartala  2022-08-05 17:00:00   56.0       56.0       55.0         NaN
18  agartala  2022-08-05 18:00:00   56.0       56.0       55.0         NaN
19  agartala  2022-08-05 19:00:00   55.0       56.0       56.0         NaN
20  agartala  2022-08-05 20:00:00   55.0       55.0       56.0         NaN
21  agartala  2022-08-05 21:00:00   55.0       55.0       56.0         NaN
22  agartala  2022-08-05 22:00:00   55.0       55.0       56.0         NaN
23  agartala  2022-08-05 23:00:00   55.0       55.0       56.0         NaN
24  agartala  2022-08-06 00:00:00   54.0       55.0       56.0       289.0
25  agartala  2022-08-06 01:00:00   54.0       54.0       55.0       289.0
26  agartala  2022-08-06 02:00:00   54.0       54.0       55.0        54.0
27  agartala  2022-08-06 03:00:00   54.0       54.0       55.0        54.0
28  agartala  2022-08-06 04:00:00   53.0       54.0       55.0        54.0
29  agartala  2022-08-06 05:00:00   53.0       53.0       55.0        54.0
30  agartala  2022-08-06 06:00:00   52.0       53.0       54.0        55.0
31  agartala  2022-08-06 07:00:00   52.0       52.0       54.0        55.0
32  agartala  2022-08-06 08:00:00   51.0       52.0       54.0        55.0
33  agartala  2022-08-06 09:00:00   51.0       51.0       54.0        54.0
34  agartala  2022-08-06 10:00:00   51.0       51.0       53.0        55.0
35  agartala  2022-08-06 11:00:00   51.0       51.0       53.0        55.0
36  agartala  2022-08-06 12:00:00   51.0       51.0       52.0        55.0
37  agartala  2022-08-06 13:00:00   51.0       51.0       52.0        56.0
38  agartala  2022-08-06 14:00:00   50.0       51.0       51.0        56.0
39  agartala  2022-08-06 15:00:00   50.0       50.0       51.0        56.0

### STEP 6 — Drop unwanted columns

In [97]:
df = df.drop(columns=[
    'city','state','latitude','longitude','datetime',
    'day_name','season','time_of_day',
    'dust_ugm3','aod',
    'aqi_category','pm25_category_india',
    'festival_period','crop_burning_season',
    'is_raining','heavy_rain'
])

In [99]:
df['is_weekend'] = df['is_weekend'].astype(str).map({
    'True': 1,
    'False': 0
}).fillna(0).astype(int)

### STEP 7 — Select final features

In [100]:
FEATURES = [
    # pollutants
    'pm2_5_ugm3','pm10_ugm3','co_ugm3','no2_ugm3','so2_ugm3','o3_ugm3',

    # time
    'hour','day_of_week','month','is_weekend',

    # location
    'city_enc',

    # lag features
    'AQI_lag_1','AQI_lag_6','AQI_lag_24'
]

joblib.dump(FEATURES, "models/features.pkl")

['models/features.pkl']

### STEP 8 — Drop NaNs

In [101]:
df = df.dropna()

### STEP 9 — Define X and y

In [102]:
X = df[FEATURES]

y_6  = df['AQI_next_6']
y_12 = df['AQI_next_12']
y_24 = df['AQI_next_24']

### STEP 10 — Train-test split

In [103]:
split = int(len(df) * 0.8)

X_train, X_test = X.iloc[:split], X.iloc[split:]
y6_train, y6_test = y_6.iloc[:split], y_6.iloc[split:]
y12_train, y12_test = y_12.iloc[:split], y_12.iloc[split:]
y24_train, y24_test = y_24.iloc[:split], y_24.iloc[split:]

### STEP 11 - Train 3 RandomForest Models

In [121]:
from sklearn.ensemble import RandomForestRegressor

rf_models = {}

for y_train, label in [
    (y6_train, "6h"),
    (y12_train, "12h"),
    (y24_train, "24h")
]:
    print(f"\nTraining RF for {label}")
    
    rf = RandomForestRegressor(
        n_estimators=200,
        random_state=42,
        n_jobs=-1,
        verbose=1
    )
    
    rf.fit(X_train, y_train)
    
    rf_models[label] = rf

Training RF for 6h

[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:   19.7s
[Parallel(n_jobs=-1)]: Done 180 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  2.1min finished
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 10 concurrent workers.

Training RF for 12h

[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:   19.2s
[Parallel(n_jobs=-1)]: Done 180 tasks      | elapsed:  1.9min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  2.1min finished
[Parallel(n_jobs=-1)]: Using backend ThreadingBackend with 10 concurrent workers.

Training RF for 24h

[Parallel(n_jobs=-1)]: Done  30 tasks      | elapsed:   20.6s
[Parallel(n_jobs=-1)]: Done 180 tasks      | elapsed:  2.0min
[Parallel(n_jobs=-1)]: Done 200 out of 200 | elapsed:  2.2min finished

### STEP 11.1 - Evaluations for the Random Forest Regressor

In [122]:
import numpy as np
from sklearn.metrics import r2_score, mean_squared_error

def evaluate_model(model, X_test, y_test, name):
    preds = model.predict(X_test)
    r2 = r2_score(y_test, preds)
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    
    print(f"{name}")
    print("R2:", r2)
    print("RMSE:", rmse)
    print()

### STEP 11 - Train 3 XGBoost Models

In [ ]:
pd.DataFrame({
    "Actual": y6_test.values[:20],
    "Predicted": model_6.predict(X_test)[:20]
})

    Actual   Predicted
0    125.0  145.416885
1    121.0  131.141159
2    118.0  123.089966
3    111.0  116.330116
4    108.0  118.194908
5    107.0  116.225098
6    107.0  115.723663
7    107.0  113.070946
8    107.0  111.170128
9    108.0  108.398315
10   108.0  105.275879
11   114.0  104.799347
12   136.0  116.351601
13   153.0  146.060455
14   160.0  151.845078
15   154.0  154.234146
16   141.0  138.377487
17   123.0  130.106873
18   110.0  117.326668
19   109.0  119.243385

In [104]:
!pip install xgboost

Requirement already satisfied: xgboost in ./venv/lib/python3.11/site-packages (3.2.0)
Requirement already satisfied: numpy in ./venv/lib/python3.11/site-packages (from xgboost) (2.4.3)
Requirement already satisfied: scipy in ./venv/lib/python3.11/site-packages (from xgboost) (1.17.1)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [105]:
from xgboost import XGBRegressor

model_6  = XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42)
model_12 = XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42)
model_24 = XGBRegressor(n_estimators=300, learning_rate=0.05, random_state=42)

model_6.fit(X_train, y6_train)
model_12.fit(X_train, y12_train)
model_24.fit(X_train, y24_train)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=300,
             n_jobs=None, num_parallel_tree=None, ...)

### STEP 12 -- EVALS

In [109]:
!pip install -U scikit-learn

Requirement already satisfied: scikit-learn in ./venv/lib/python3.11/site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in ./venv/lib/python3.11/site-packages (from scikit-learn) (2.4.3)
Requirement already satisfied: scipy>=1.10.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.3.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in ./venv/lib/python3.11/site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0 -> 26.0.1
[notice] To update, run: pip install --upgrade pip

In [111]:
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np

def evaluate(y_true, y_pred, name):
    print(f"==== {name} ====")
    print("R2   :", r2_score(y_true, y_pred))
    
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    
    print("RMSE :", rmse)
    print()

In [112]:
evaluate(y6_test, model_6.predict(X_test), "6h")
evaluate(y12_test, model_12.predict(X_test), "12h")
evaluate(y24_test, model_24.predict(X_test), "24h")

==== 6h ====
R2   : 0.970813164862302
RMSE : 6.744911115104681

==== 12h ====
R2   : 0.9043127591234664
RMSE : 12.213651545519935

==== 24h ====
R2   : 0.7745511813432562
RMSE : 18.75464663062243

### Verifying Predictions

In [113]:
pd.DataFrame({
    "Actual": y6_test.values[:20],
    "Predicted": model_6.predict(X_test)[:20]
})

    Actual   Predicted
0    125.0  145.416885
1    121.0  131.141159
2    118.0  123.089966
3    111.0  116.330116
4    108.0  118.194908
5    107.0  116.225098
6    107.0  115.723663
7    107.0  113.070946
8    107.0  111.170128
9    108.0  108.398315
10   108.0  105.275879
11   114.0  104.799347
12   136.0  116.351601
13   153.0  146.060455
14   160.0  151.845078
15   154.0  154.234146
16   141.0  138.377487
17   123.0  130.106873
18   110.0  117.326668
19   109.0  119.243385

In [117]:
joblib.dump(model_6,  "models/xgb_6h.pkl")
joblib.dump(model_12, "models/xgb_12h.pkl")
joblib.dump(model_24, "models/xgb_24h.pkl")
joblib.dump(FEATURES, "models/features.pkl")
joblib.dump(le, "models/city_encoder.pkl")

['models/city_encoder.pkl']

### QUICK TEST

In [118]:
m6 = joblib.load("models/xgb_6h.pkl")

sample = X_test.iloc[0].values.reshape(1, -1)
print(m6.predict(sample))

[145.41689]

In [ ]:
pd.DataFrame({
    "Actual": y6_test.values[:20],
    "Predicted": model_6.predict(X_test)[:20]
})

    Actual   Predicted
0    125.0  145.416885
1    121.0  131.141159
2    118.0  123.089966
3    111.0  116.330116
4    108.0  118.194908
5    107.0  116.225098
6    107.0  115.723663
7    107.0  113.070946
8    107.0  111.170128
9    108.0  108.398315
10   108.0  105.275879
11   114.0  104.799347
12   136.0  116.351601
13   153.0  146.060455
14   160.0  151.845078
15   154.0  154.234146
16   141.0  138.377487
17   123.0  130.106873
18   110.0  117.326668
19   109.0  119.243385

In [123]:
print("===== RANDOM FOREST =====")
evaluate_model(rf_models["6h"], X_test, y6_test, "RF 6h")
evaluate_model(rf_models["12h"], X_test, y12_test, "RF 12h")
evaluate_model(rf_models["24h"], X_test, y24_test, "RF 24h")

===== RANDOM FOREST =====

[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.4s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    2.7s
[Parallel(n_jobs=10)]: Done 200 out of 200 | elapsed:    3.1s finished
[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.

RF 6h
R2: 0.9704671958090201
RMSE: 6.784769085346224

[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.5s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    2.7s
[Parallel(n_jobs=10)]: Done 200 out of 200 | elapsed:    2.9s finished
[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.

RF 12h
R2: 0.8904385266925002
RMSE: 13.069152971921167

[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.5s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    3.0s
[Parallel(n_jobs=10)]: Done 200 out of 200 | elapsed:    3.2s finished

RF 24h
R2: 0.8199502354901002
RMSE: 16.760276635972904

In [124]:
print("===== XGBOOST =====")
evaluate_model(model_6, X_test, y6_test, "XGB 6h")
evaluate_model(model_12, X_test, y12_test, "XGB 12h")
evaluate_model(model_24, X_test, y24_test, "XGB 24h")

===== XGBOOST =====
XGB 6h
R2: 0.970813164862302
RMSE: 6.744911115104681

XGB 12h
R2: 0.9043127591234664
RMSE: 12.213651545519935

XGB 24h
R2: 0.7745511813432562
RMSE: 18.75464663062243

In [125]:
import pandas as pd

results = []

def collect_results(model, X_test, y_test, name):
    preds = model.predict(X_test)
    results.append({
        "Model": name,
        "R2": r2_score(y_test, preds),
        "RMSE": np.sqrt(mean_squared_error(y_test, preds))
    })

# RF
collect_results(rf_models["6h"], X_test, y6_test, "RF 6h")
collect_results(rf_models["12h"], X_test, y12_test, "RF 12h")
collect_results(rf_models["24h"], X_test, y24_test, "RF 24h")

# XGB
collect_results(model_6, X_test, y6_test, "XGB 6h")
collect_results(model_12, X_test, y12_test, "XGB 12h")
collect_results(model_24, X_test, y24_test, "XGB 24h")

pd.DataFrame(results)

[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.5s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    3.3s
[Parallel(n_jobs=10)]: Done 200 out of 200 | elapsed:    3.5s finished
[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.5s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    2.6s
[Parallel(n_jobs=10)]: Done 200 out of 200 | elapsed:    2.9s finished
[Parallel(n_jobs=10)]: Using backend ThreadingBackend with 10 concurrent workers.
[Parallel(n_jobs=10)]: Done  30 tasks      | elapsed:    0.6s
[Parallel(n_jobs=10)]: Done 180 tasks      | elapsed:    3.0s
[Parallel(n_jobs=10)]: Done 200 out of 200 | elapsed:    3.2s finished

     Model        R2       RMSE
0    RF 6h  0.970467   6.784769
1   RF 12h  0.890439  13.069153
2   RF 24h  0.819950  16.760277
3   XGB 6h  0.970813   6.744911
4  XGB 12h  0.904313  12.213652
5  XGB 24h  0.774551  18.754647

### Random Forest Regressor for 24 hours

In [128]:
rf_24 = rf_models["24h"]
joblib.dump(rf_24, "models/rf_24h.pkl")

['models/rf_24h.pkl']